:includedir: _includes

= Algorithm to process csv files

== Format:
....
[%autowidth%header, format=csv, separator=,]
|===
\include::{includedir}\FieldAgents.csv[cols="1,5,6"]
|===
....

== Reference from adoc manual

link:https://asciidoctor.org/docs/user-manual/#include-directive[adoc manual include-directive]

The include directive must be placed on a line by itself with the following syntax
....
\include::path[<attrlist>]
....

The include directive has the following anatomy:
....
\include::path[leveloffset=offset,lines=ranges,tag(s)=name(s),indent=depth,opts=optional]
....

The leveloffset, lines, tag(s), indent, and opt attributes are optional, making the simplest case look like:
....
\include::content.adoc[]
....

Including non-AsciiDoc files is normally done to merge output from other programs or populate table data:
....
.2016 Sales Results
,===
\include::sales/2016/results.csv[]
,===
....
In this case, the include directive does not do any processing of AsciiDoc directives. The content is inserted as is (after being normalized).


== Handle csv with ruby
link:https://www.rubyguides.com/2018/10/parse-csv-ruby/[How to Read & Parse CSV Files With Ruby] +
link:https://www.rubydoc.info/gems/fastercsv/1.5.5/file/README[Fastercsv] +
link:https://stackoverflow.com/questions/4821843/changing-field-separator-delimiter-in-exported-csv-using-ruby-csv[csv separator]
link:https://ruby-doc.org/stdlib-2.6.1/libdoc/csv/rdoc/CSV.html[ruby doc csv]
link:https://stackoverflow.com/questions/7911669/how-to-create-a-file-in-ruby[create file]

== requirement

To include content by column range, begin with start column end with end column and separate them with two dot (e.g., columns=1..5) to the columns attribute.

```asciidoc
\include::filename.csv[columns=1..3]
```
You could have multiple ranges separate with comma. Quote the list of ranges as commas are normally to separate individual attributes.

```asciidoc
\include::filename.csv[columns="1..3,10..14"]
```

You can use semi-colons to separate ranges to instead the quote and commas combination.

```asciidoc
\include::filename.csv[columns=1;5..8;10..15]
```

You can refer to the last column of the document using the value -1.

```asciidoc
\include::filename.csv[columns=3..-1]
```

== extentions IncludeProcessors

link:https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/extensions.rb[IncludeProcessors Line 436]

....
# Public: IncludeProcessors are used to process `include::<target>[]`
# directives in the source document.
#
# When Asciidoctor comes across a `include::<target>[]` directive in the
# source document, it iterates through the IncludeProcessors and delegates
# the work of reading the content to the first processor that identifies
# itself as capable of handling that target.
#
# IncludeProcessor implementations must extend IncludeProcessor.
#--
# TODO add file extension or regexp as shortcut for handles? method
....


== asciidoctor methods

link:https://github.com/asciidoctor/asciidoctor/blob/2dbbb04f6cd3c4728a2e24918814e30d642a6305/lib/asciidoctor/reader.rb[reader.push_include line#662] +
link:https://github.com/asciidoctor/asciidoctorj/issues/800[clarification of PreprocessorReader.push_include(..)] +
link:https://github.com/asciidoctor/asciidoctorj/blob/master/docs/integrator-guide.adoc#include-processors[include processor java] +
link:https://www.rubydoc.info/gems/asciidoctor/1.5.5[ruby asciidoctor IMPORTANT]

== Pseudocode

Define target *.csv
columns Attribute in adoc [columns = ""]

range list: 1..5
individual: 1,2,3 OR 1;2;3
last line: -1

switch separator
  case ",": must quote the list ranges
    individual "1,3,5"
    range      "1..5, 8..10"
    break;
  case ";":
    individual 1;3;5
    range      1..5; 8..10
