:imagesdir: media
:includedir: _includes
:toc:

= Asciidoctor-CSV-SubColumn
Author: Guanping Yu <yugp2005@gmail.com>

Select sub column in asciidoctor CSV table to form new table. +
Similar function
link:https://asciidoctor.org/docs/user-manual/#by-line-ranges[28.6.3 asciidoctor by-line-ranges]

To include content by column range, begin with start column end with end column and separate them with two dot (e.g., columns=1..5) to the columns attribute.

```asciidoc
\include::filename.csv[columns=1..3]
```
You could have multiple ranges separate with comma. Quote the list of ranges as commas are normally to separate individual attributes.

```asciidoc
\include::filename.csv[columns="1..3,10..14"]
```

You can use semi-colons to separate ranges to instead the quote and commas combination.

```asciidoc
\include::filename.csv[columns=1;5..8;10..15]
```

== Example
* Original csv file

```asciidoc
[%autowidth%header, format=csv, separator=,]
|===
\include::{includedir}\FieldAgents.csv[]
|===
```

[%autowidth%header, format=csv, separator=,]
|===
include::{includedir}\FieldAgents.csv[]
|===

* New csv file with choose sub column
```asciidoc
[%autowidth%header, format=csv, separator=,]
|===
\include::{includedir}\FieldAgents.csv[columns="1,4,5", column_separator=","]
|===
```

OR

```asciidoc
[%autowidth%header, format=csv, separator=,]
|===
\include::{includedir}\FieldAgents.csv[columns=1;4;5, column_separator=","]
|===
```


[%autowidth%header, format=csv, separator=,]
|===
include::{includedir}\SubFieldAgents.csv[]
|===

== Disscussions
There are some topic on this issue, such as:

* Asciidoctor github issue #2101
include::https://github.com/asciidoctor/asciidoctor/issues/2101[including sub columns of a csv file in a table]

* related topic
link:https://github.com/asciidoctor/asciidoctor-extensions-lab[Extension lab]
link:https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/textql-block.rb[textql-block]
link:https://github.com/dinedal/textql[textql]

== Using extension
link:https://github.com/asciidoctor/asciidoctor-extensions-lab[Reference asciidoctor-extensions-lab]

First, make sure Asciidoctor is installed:

 $ gem install asciidoctor

Next, run the extension from the root directory of the project:

  $ asciidoctor -r ./lib/csvsubcolumn-include-processor.rb lib/csvsubcolumn-include-processor/sample.adoc

The output file, [path]_sample.html_, was created in the same directory as the source file, [path]_sample.adoc_.

The relevant bits of the input and output are shown below.

._lib/csvsubcolumn-include-processor/sample.adoc_
```asciidoc
:includedir: ..\..\_includes

= csvSubColumn Include Processor

.Example of FieldAgents.csv--Original
[%autowidth%header, format=csv, separator=,]
|===
\include::{includedir}\FieldAgents.csv[]
|===

.Example of FieldAgents.csv with SubColumn
[%autowidth%header, format=csv, separator=,]
|===
\include::{includedir}\FieldAgents.csv[cols=1;5;6]
|===
```

._lib/csvsubcolumn-include-processor/sample.html_
```html
TODO
```

== TODO
You can refer to the last column of the document using the value -1.

```asciidoc
\include::filename.csv[columns=3..-1]
```
